development:
  clients:
    default:
      database: gamebot_development
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

test:
  clients:
    default:
      database: gamebot_test
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URI'] || ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
    use_utc: true
